### ISSUE TITLE
Error: Contract Error [get]: Error: Database is not open

### ISSUE THREAD

**Issue by fukaoi** [firstbatchxyz/hollowdb#47]
Hi

I get this error when I run the following code. What could be the cause?

```
2023-08-05T11:54:06.505Z FATAL [HandlerBasedContract] Error while interacting
 with contract [
  {
    type: 'exception',
    error: 'Error: Database is not open\n' +
      '    at maybeOpened (hollowdb/node_modules/abstract-level/abstract-level.js:133:18)\n' +
      '    at hollowdb/node_modules/abstract-level/abstract-level.js:160:13\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)'
  }
]
```
These codes causes an error.

* pattern1

```
  const keys = await sdk.getAllKeys();
  const values = await sdk.getMany(keys);
```

* pattern2

```
  const keys = await sdk.getAllKeys();
   keys.map(async key => {
    const value = await sdk.get(key);
  });
```

The same error occurred after deleting the cache directory.
Please response me.

**Comment by erhant** [comment]
Hey,

Could you show us how you instantiate Warp and HollowDB? There may be something about the cache that is used in the background. Also, which platform is this? (e.g. React)

**Comment by fukaoi** [comment]
@erhant 

My operating environment.

* OS: Linux
* Node.js: v18.12.1

I am running it in Node.js on my pc terminal.
 Just run the following in cli.

```bash
$node demo.js
```


this is full source code.


### demo.js
```js
const {SDK} = require('hollowdb');
const {WarpFactory} = require('warp-contracts');
const fs = require('fs');

async function main() {
  const wallet = JSON.parse(fs.readFileSync('./wallet.json').toString());
  const contractTxId = 'ux1KD0dalkbIY-dB3quNKu3YinE0hG0_ZySSYqC7suc';
  const warp = WarpFactory.forMainnet();
  const sdk = new SDK(wallet, contractTxId, warp);

  const keys = await sdk.getAllKeys();
  const values = await sdk.getMany(keys);
  console.log('#values: ', values);

  // keys.map(async key => {
  //   const value = await sdk.get(key);
  //   console.log(value);
  // });
}

main();
```

### package.json
```json
{
  "name": "hollowdb-example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "hollowdb": "^1.2.4",
    "warp-contracts": "^1.4.14"
  }
}
```

**Comment by erhant** [comment]
Hi, 

First, sorry that is has been such a long time since the issue was opened!

The problem is due to `SortKeyCache` used by Warp, which calls `open` and `close` functions for each interaction, at the start and at the end. This means that the database is always closed, and is only opened during an interaction (whether it be LMDB, Redis or whatever).

When we call this concurrently such as via `Promise.all`, we may run into the problem of calling `close` right after `open` when an interaction is still in progress, thus resulting in th error.

The reason this was not caught in tests is simple: `getMany` turned out to be not tested..

Our own Redis implementation (https://www.npmjs.com/package/warp-contracts-redis) has a workaround for this, where the user passes in the Redis client manually and is responsible from calling `open` and `close` for the client themselves, thereby allowing for multi-interactions.

I am currently on fixing this issue, where a `getMany` and `putMany` will be added that, which is a single interaction with an array for arguments. This too does not help with everything, due to the interaction size limit within Warp (1mb) so the user must make a series of these calls; or just use Redis with your own client.

I will mention this issue in the PR.
